include: package:aeb_lint/analysis_options.yaml

analyzer:
  language:
    strict-casts: false

linter:
  rules:
    always_specify_types: false
    avoid_dynamic_calls: false
    cascade_invocations: false
    parameter_assignments: false
