name: steamworks_gen
description: A command-line tool to generate Steamworks SDK in a darty way
version: 0.2.4
homepage: https://github.com/aeb-dev/steamworks_gen
repository: https://github.com/aeb-dev/steamworks_gen
issues: https://github.com/aeb-dev/steamworks_gen/issues

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  recase: ^4.0.0
  path: ^1.8.0
  args: ^2.3.0
  cli_util: ^0.3.5

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

platforms:
  linux:
  macos:
  windows:
